// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for how does it work documents
 */
interface HowDoesItWorkDocumentData {
  /**
   * title field in *how does it work*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_does_it_work.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *how does it work*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_does_it_work.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * how does it work document from Prismic
 *
 * - **API ID**: `how_does_it_work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HowDoesItWorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HowDoesItWorkDocumentData>,
    "how_does_it_work",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | WhyEuropeSlice
  | TripRecomendationsSlice
  | ContactFormSlice
  | ReasonsSlice
  | OurTeamSlice
  | HotelsSlice
  | RoutesConditionsSlice
  | RouteHeroSlice
  | RoutesDescriptionSlice
  | AdvantagesSlice
  | ForMoreInfoContactSlice
  | InsuranceSlice
  | SurvivorsSlice
  | MundorailRoutesSlice
  | OurRoutesSlice
  | FooterSlice
  | CustomBudgetsSlice
  | TestimonailsSlice
  | HowDoesItWorkSlice
  | ContactUsSlice
  | RouteCardSlice
  | HeroSlice
  | NavigationSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for reasons documents
 */
interface ReasonsDocumentData {
  /**
   * title field in *reasons*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *reasons*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * reasons document from Prismic
 *
 * - **API ID**: `reasons`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReasonsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ReasonsDocumentData>,
    "reasons",
    Lang
  >;

/**
 * Content for route documents
 */
interface RouteCardDocumentData {
  /**
   * days field in *route*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.days
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  days: prismic.KeyTextField;

  /**
   * price field in *route*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * subtitle field in *route*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * route image field in *route*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.route_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  route_image: prismic.ImageField<never>;

  /**
   * description field in *route*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * notes field in *route*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.notes
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  notes: prismic.RichTextField;

  /**
   * conditions field in *route*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.conditions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conditions: prismic.RichTextField;

  /**
   * signature image field in *route*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.signature_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  signature_image: prismic.ImageField<never>;

  /**
   * title field in *route*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * pdf field in *route*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.pdf
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  pdf: prismic.LinkToMediaField;

  /**
   * special description field in *route*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.special_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  special_description: prismic.RichTextField;
}

/**
 * route document from Prismic
 *
 * - **API ID**: `route_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RouteCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RouteCardDocumentData>,
    "route_card",
    Lang
  >;

/**
 * Content for routes documents
 */
interface RoutesDocumentData {
  /**
   * title field in *routes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: routes.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * long title field in *routes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: routes.long_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  long_title: prismic.RichTextField;

  /**
   * short description field in *routes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: routes.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  short_description: prismic.RichTextField;

  /**
   * description field in *routes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: routes.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * background image field in *routes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: routes.background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * routes document from Prismic
 *
 * - **API ID**: `routes`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RoutesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<RoutesDocumentData>, "routes", Lang>;

/**
 * Content for testimonail documents
 */
interface TestimonailDocumentData {
  /**
   * name field in *testimonail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonail.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * review field in *testimonail*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonail.review
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  review: prismic.RichTextField;

  /**
   * number of starts from 1 to 5 field in *testimonail*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonail.number_of_starts_from_1_to_5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  number_of_starts_from_1_to_5: prismic.NumberField;
}

/**
 * testimonail document from Prismic
 *
 * - **API ID**: `testimonail`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonailDocumentData>,
    "testimonail",
    Lang
  >;

/**
 * Content for whyEurope documents
 */
interface WhyeuropeDocumentData {
  /**
   * title field in *whyEurope*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyeurope.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *whyEurope*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyeurope.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *whyEurope*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: whyeurope.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * whyEurope document from Prismic
 *
 * - **API ID**: `whyeurope`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WhyeuropeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WhyeuropeDocumentData>,
    "whyeurope",
    Lang
  >;

export type AllDocumentTypes =
  | HowDoesItWorkDocument
  | PageDocument
  | ReasonsDocument
  | RouteCardDocument
  | RoutesDocument
  | TestimonailDocument
  | WhyeuropeDocument;

/**
 * Primary content in *Advantages → Default → Primary*
 */
export interface AdvantagesSliceDefaultPrimary {
  /**
   * Title field in *Advantages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Advantages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *Advantages → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * image field in *Advantages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * cta link field in *Advantages → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for Advantages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvantagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AdvantagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Advantages*
 */
type AdvantagesSliceVariation = AdvantagesSliceDefault;

/**
 * Advantages Shared Slice
 *
 * - **API ID**: `advantages`
 * - **Description**: Advantages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvantagesSlice = prismic.SharedSlice<
  "advantages",
  AdvantagesSliceVariation
>;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * title field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitile field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.subtitile
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitile: prismic.RichTextField;

  /**
   * description field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * cta link field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *ContactUs → Default → Primary*
 */
export interface ContactUsSliceDefaultPrimary {
  /**
   * text field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * cta field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * image field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * cta link field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for ContactUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactUs*
 */
type ContactUsSliceVariation = ContactUsSliceDefault;

/**
 * ContactUs Shared Slice
 *
 * - **API ID**: `contact_us`
 * - **Description**: ContactUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsSlice = prismic.SharedSlice<
  "contact_us",
  ContactUsSliceVariation
>;

/**
 * Primary content in *CustomBudgets → Default → Primary*
 */
export interface CustomBudgetsSliceDefaultPrimary {
  /**
   * title field in *CustomBudgets → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_budgets.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *CustomBudgets → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_budgets.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *CustomBudgets → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_budgets.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * image field in *CustomBudgets → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_budgets.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * cta link field in *CustomBudgets → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_budgets.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for CustomBudgets Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomBudgetsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CustomBudgetsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CustomBudgets*
 */
type CustomBudgetsSliceVariation = CustomBudgetsSliceDefault;

/**
 * CustomBudgets Shared Slice
 *
 * - **API ID**: `custom_budgets`
 * - **Description**: CustomBudgets
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomBudgetsSlice = prismic.SharedSlice<
  "custom_budgets",
  CustomBudgetsSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * logo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * left image field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.left_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  left_image: prismic.ImageField<never>;

  /**
   * number field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * street field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.street
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  street: prismic.RichTextField;

  /**
   * disclaimer field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.disclaimer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  disclaimer: prismic.RichTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *ForMoreInfoContact → Default → Primary*
 */
export interface ForMoreInfoContactSliceDefaultPrimary {
  /**
   * title field in *ForMoreInfoContact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_more_info_contact.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *ForMoreInfoContact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_more_info_contact.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * cta field in *ForMoreInfoContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_more_info_contact.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * background image field in *ForMoreInfoContact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: for_more_info_contact.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * cta link field in *ForMoreInfoContact → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: for_more_info_contact.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for ForMoreInfoContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ForMoreInfoContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ForMoreInfoContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ForMoreInfoContact*
 */
type ForMoreInfoContactSliceVariation = ForMoreInfoContactSliceDefault;

/**
 * ForMoreInfoContact Shared Slice
 *
 * - **API ID**: `for_more_info_contact`
 * - **Description**: ForMoreInfoContact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ForMoreInfoContactSlice = prismic.SharedSlice<
  "for_more_info_contact",
  ForMoreInfoContactSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * hero field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero: prismic.ImageField<never>;

  /**
   * secondary title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondary_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_title: prismic.KeyTextField;

  /**
   * secondary image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondary_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  secondary_image: prismic.ImageField<never>;

  /**
   * first option field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.first_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_option: prismic.KeyTextField;

  /**
   * second option field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.second_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_option: prismic.KeyTextField;

  /**
   * third option field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.third_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  third_option: prismic.KeyTextField;

  /**
   * forth option field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.forth_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  forth_option: prismic.KeyTextField;

  /**
   * fifth option field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.fifth_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fifth_option: prismic.KeyTextField;

  /**
   * sixth option field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.sixth_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sixth_option: prismic.KeyTextField;

  /**
   * seventh option field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.seventh_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seventh_option: prismic.KeyTextField;

  /**
   * eight option field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.eight_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eight_option: prismic.KeyTextField;

  /**
   * cta field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * cta_text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * secondary description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondary_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  secondary_description: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Hotels → Default → Primary*
 */
export interface HotelsSliceDefaultPrimary {
  /**
   * title field in *Hotels → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hotels.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hotels → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hotels.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * second description field in *Hotels → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hotels.default.primary.second_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_description: prismic.RichTextField;

  /**
   * images field in *Hotels → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hotels.default.primary.images
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  images: prismic.ImageField<never>;

  /**
   * cta field in *Hotels → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hotels.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * isSurvivors field in *Hotels → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hotels.default.primary.issurvivors
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  issurvivors: prismic.BooleanField;

  /**
   * cta_link field in *Hotels → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hotels.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for Hotels Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HotelsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HotelsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hotels*
 */
type HotelsSliceVariation = HotelsSliceDefault;

/**
 * Hotels Shared Slice
 *
 * - **API ID**: `hotels`
 * - **Description**: Hotels
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HotelsSlice = prismic.SharedSlice<"hotels", HotelsSliceVariation>;

/**
 * Primary content in *HowDoesItWork → Default → Primary*
 */
export interface HowDoesItWorkSliceDefaultPrimary {
  /**
   * title field in *HowDoesItWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_does_it_work.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * cta field in *HowDoesItWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_does_it_work.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * cta link field in *HowDoesItWork → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: how_does_it_work.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * alternative title field in *HowDoesItWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_does_it_work.default.primary.alternative_title
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  alternative_title: prismic.ImageField<never>;
}

/**
 * Primary content in *HowDoesItWork → Items*
 */
export interface HowDoesItWorkSliceDefaultItem {
  /**
   * how does it work field in *HowDoesItWork → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: how_does_it_work.items[].how_does_it_work
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  how_does_it_work: prismic.ContentRelationshipField<"reasons">;
}

/**
 * Default variation for HowDoesItWork Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowDoesItWorkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HowDoesItWorkSliceDefaultPrimary>,
  Simplify<HowDoesItWorkSliceDefaultItem>
>;

/**
 * Slice variation for *HowDoesItWork*
 */
type HowDoesItWorkSliceVariation = HowDoesItWorkSliceDefault;

/**
 * HowDoesItWork Shared Slice
 *
 * - **API ID**: `how_does_it_work`
 * - **Description**: HowDoesItWork
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowDoesItWorkSlice = prismic.SharedSlice<
  "how_does_it_work",
  HowDoesItWorkSliceVariation
>;

/**
 * Primary content in *Insurance → Default → Primary*
 */
export interface InsuranceSliceDefaultPrimary {
  /**
   * Title field in *Insurance → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Insurance → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * description field in *Insurance → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *Insurance → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * preview field in *Insurance → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance.default.primary.preview
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  preview: prismic.RichTextField;

  /**
   * full_insurance field in *Insurance → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance.default.primary.full_insurance
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  full_insurance: prismic.RichTextField;

  /**
   * cta link field in *Insurance → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * coverage field in *Insurance → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance.default.primary.coverage
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  coverage: prismic.RichTextField;
}

/**
 * Default variation for Insurance Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InsuranceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InsuranceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Insurance*
 */
type InsuranceSliceVariation = InsuranceSliceDefault;

/**
 * Insurance Shared Slice
 *
 * - **API ID**: `insurance`
 * - **Description**: Insurance
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InsuranceSlice = prismic.SharedSlice<
  "insurance",
  InsuranceSliceVariation
>;

/**
 * Primary content in *MundorailRoutes → Default → Primary*
 */
export interface MundorailRoutesSliceDefaultPrimary {
  /**
   * title field in *MundorailRoutes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mundorail_routes.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta field in *MundorailRoutes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mundorail_routes.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * cta link field in *MundorailRoutes → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mundorail_routes.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * alternative title field in *MundorailRoutes → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mundorail_routes.default.primary.alternative_title
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  alternative_title: prismic.ImageField<never>;
}

/**
 * Primary content in *MundorailRoutes → Items*
 */
export interface MundorailRoutesSliceDefaultItem {
  /**
   * routes field in *MundorailRoutes → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: mundorail_routes.items[].routes
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  routes: prismic.ContentRelationshipField<"routes">;
}

/**
 * Default variation for MundorailRoutes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MundorailRoutesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MundorailRoutesSliceDefaultPrimary>,
  Simplify<MundorailRoutesSliceDefaultItem>
>;

/**
 * Slice variation for *MundorailRoutes*
 */
type MundorailRoutesSliceVariation = MundorailRoutesSliceDefault;

/**
 * MundorailRoutes Shared Slice
 *
 * - **API ID**: `mundorail_routes`
 * - **Description**: MundorailRoutes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MundorailRoutesSlice = prismic.SharedSlice<
  "mundorail_routes",
  MundorailRoutesSliceVariation
>;

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
  /**
   * page 1 field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.page_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_1: prismic.LinkField;

  /**
   * page 2 field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.page_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_2: prismic.LinkField;

  /**
   * logo field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * page 3 field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.page_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_3: prismic.LinkField;

  /**
   * page 4 field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.page_4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_4: prismic.LinkField;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Navigation → Negative → Primary*
 */
export interface NavigationSliceNegativePrimary {
  /**
   * page 1 field in *Navigation → Negative → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.negative.primary.page_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_1: prismic.LinkField;

  /**
   * page 2 field in *Navigation → Negative → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.negative.primary.page_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_2: prismic.LinkField;

  /**
   * logo field in *Navigation → Negative → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.negative.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * page 3 field in *Navigation → Negative → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.negative.primary.page_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_3: prismic.LinkField;

  /**
   * page 4 field in *Navigation → Negative → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.negative.primary.page_4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_4: prismic.LinkField;
}

/**
 * Negative variation for Navigation Slice
 *
 * - **API ID**: `negative`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceNegative = prismic.SharedSliceVariation<
  "negative",
  Simplify<NavigationSliceNegativePrimary>,
  never
>;

/**
 * Primary content in *Navigation → Positive → Primary*
 */
export interface NavigationSlicePositivePrimary {
  /**
   * page 1 field in *Navigation → Positive → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.positive.primary.page_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_1: prismic.LinkField;

  /**
   * page 2 field in *Navigation → Positive → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.positive.primary.page_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_2: prismic.LinkField;

  /**
   * logo field in *Navigation → Positive → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.positive.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * page 3 field in *Navigation → Positive → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.positive.primary.page_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_3: prismic.LinkField;

  /**
   * page 4 field in *Navigation → Positive → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.positive.primary.page_4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_4: prismic.LinkField;
}

/**
 * Positive variation for Navigation Slice
 *
 * - **API ID**: `positive`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlicePositive = prismic.SharedSliceVariation<
  "positive",
  Simplify<NavigationSlicePositivePrimary>,
  never
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation =
  | NavigationSliceDefault
  | NavigationSliceNegative
  | NavigationSlicePositive;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<
  "navigation",
  NavigationSliceVariation
>;

/**
 * Primary content in *OurRoutes → Default → Primary*
 */
export interface OurRoutesSliceDefaultPrimary {
  /**
   * title field in *OurRoutes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_routes.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *OurRoutes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_routes.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *OurRoutes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_routes.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * image field in *OurRoutes → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_routes.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * cta link field in *OurRoutes → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: our_routes.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for OurRoutes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurRoutesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurRoutesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurRoutes*
 */
type OurRoutesSliceVariation = OurRoutesSliceDefault;

/**
 * OurRoutes Shared Slice
 *
 * - **API ID**: `our_routes`
 * - **Description**: OurRoutes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurRoutesSlice = prismic.SharedSlice<
  "our_routes",
  OurRoutesSliceVariation
>;

/**
 * Primary content in *OurTeam → Default → Primary*
 */
export interface OurTeamSliceDefaultPrimary {
  /**
   * title field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for OurTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurTeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurTeam*
 */
type OurTeamSliceVariation = OurTeamSliceDefault;

/**
 * OurTeam Shared Slice
 *
 * - **API ID**: `our_team`
 * - **Description**: OurTeam
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurTeamSlice = prismic.SharedSlice<
  "our_team",
  OurTeamSliceVariation
>;

/**
 * Primary content in *Reasons → Default → Primary*
 */
export interface ReasonsSliceDefaultPrimary {
  /**
   * title field in *Reasons → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Reasons → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *Reasons → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * cta link field in *Reasons → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Primary content in *Reasons → Items*
 */
export interface ReasonsSliceDefaultItem {
  /**
   * reasons field in *Reasons → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons.items[].reasons
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  reasons: prismic.ContentRelationshipField<"how_does_it_work">;
}

/**
 * Default variation for Reasons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReasonsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReasonsSliceDefaultPrimary>,
  Simplify<ReasonsSliceDefaultItem>
>;

/**
 * Slice variation for *Reasons*
 */
type ReasonsSliceVariation = ReasonsSliceDefault;

/**
 * Reasons Shared Slice
 *
 * - **API ID**: `reasons`
 * - **Description**: Reasons
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReasonsSlice = prismic.SharedSlice<
  "reasons",
  ReasonsSliceVariation
>;

/**
 * Primary content in *Routes → Default → Primary*
 */
export interface RouteCardSliceDefaultPrimary {
  /**
   * cta field in *Routes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * title field in *Routes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta_link field in *Routes → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * shouldShowFilter field in *Routes → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: route_card.default.primary.shouldshowfilter
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  shouldshowfilter: prismic.BooleanField;

  /**
   * shouldSpaceOut field in *Routes → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: route_card.default.primary.shouldspaceout
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  shouldspaceout: prismic.BooleanField;
}

/**
 * Primary content in *Routes → Items*
 */
export interface RouteCardSliceDefaultItem {
  /**
   * route card field in *Routes → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: route_card.items[].route_card
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  route_card: prismic.ContentRelationshipField<"route_card">;
}

/**
 * Default variation for Routes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RouteCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RouteCardSliceDefaultPrimary>,
  Simplify<RouteCardSliceDefaultItem>
>;

/**
 * Slice variation for *Routes*
 */
type RouteCardSliceVariation = RouteCardSliceDefault;

/**
 * Routes Shared Slice
 *
 * - **API ID**: `route_card`
 * - **Description**: RouteCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RouteCardSlice = prismic.SharedSlice<
  "route_card",
  RouteCardSliceVariation
>;

/**
 * Primary content in *RouteHero → Default → Primary*
 */
export interface RouteHeroSliceDefaultPrimary {
  /**
   * route field in *RouteHero → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: route_hero.default.primary.route
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  route: prismic.ContentRelationshipField;

  /**
   * isSurvivors field in *RouteHero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: route_hero.default.primary.issurvivors
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  issurvivors: prismic.BooleanField;

  /**
   * background_image field in *RouteHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: route_hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for RouteHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RouteHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RouteHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RouteHero*
 */
type RouteHeroSliceVariation = RouteHeroSliceDefault;

/**
 * RouteHero Shared Slice
 *
 * - **API ID**: `route_hero`
 * - **Description**: RouteHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RouteHeroSlice = prismic.SharedSlice<
  "route_hero",
  RouteHeroSliceVariation
>;

/**
 * Primary content in *RoutesConditions → Default → Primary*
 */
export interface RoutesConditionsSliceDefaultPrimary {
  /**
   * route field in *RoutesConditions → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: routes_conditions.default.primary.route
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  route: prismic.ContentRelationshipField<"route_card">;

  /**
   * isSurvivors field in *RoutesConditions → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: routes_conditions.default.primary.issurvivors
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  issurvivors: prismic.BooleanField;
}

/**
 * Default variation for RoutesConditions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RoutesConditionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RoutesConditionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RoutesConditions*
 */
type RoutesConditionsSliceVariation = RoutesConditionsSliceDefault;

/**
 * RoutesConditions Shared Slice
 *
 * - **API ID**: `routes_conditions`
 * - **Description**: RoutesConditions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RoutesConditionsSlice = prismic.SharedSlice<
  "routes_conditions",
  RoutesConditionsSliceVariation
>;

/**
 * Primary content in *RoutesDescription → Default → Primary*
 */
export interface RoutesDescriptionSliceDefaultPrimary {
  /**
   * routes field in *RoutesDescription → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: routes_description.default.primary.routes
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  routes: prismic.ContentRelationshipField<"routes">;

  /**
   * alternative title field in *RoutesDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: routes_description.default.primary.alternative_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  alternative_title: prismic.RichTextField;

  /**
   * cta field in *RoutesDescription → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: routes_description.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * cta link field in *RoutesDescription → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: routes_description.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for RoutesDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RoutesDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RoutesDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RoutesDescription*
 */
type RoutesDescriptionSliceVariation = RoutesDescriptionSliceDefault;

/**
 * RoutesDescription Shared Slice
 *
 * - **API ID**: `routes_description`
 * - **Description**: RoutesDescription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RoutesDescriptionSlice = prismic.SharedSlice<
  "routes_description",
  RoutesDescriptionSliceVariation
>;

/**
 * Primary content in *Survivors → Default → Primary*
 */
export interface SurvivorsSliceDefaultPrimary {
  /**
   * description field in *Survivors → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: survivors.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *Survivors → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: survivors.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * cta link field in *Survivors → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: survivors.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for Survivors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SurvivorsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SurvivorsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Survivors*
 */
type SurvivorsSliceVariation = SurvivorsSliceDefault;

/**
 * Survivors Shared Slice
 *
 * - **API ID**: `survivors`
 * - **Description**: Survivors
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SurvivorsSlice = prismic.SharedSlice<
  "survivors",
  SurvivorsSliceVariation
>;

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonailsSliceDefaultPrimary {
  /**
   * title field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonails.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * background image field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonails.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Testimonial → Items*
 */
export interface TestimonailsSliceDefaultItem {
  /**
   * testimonial field in *Testimonial → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonails.items[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  testimonial: prismic.ContentRelationshipField<"testimonail">;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonailsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonailsSliceDefaultPrimary>,
  Simplify<TestimonailsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonailsSliceVariation = TestimonailsSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonails`
 * - **Description**: Testimonails
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonailsSlice = prismic.SharedSlice<
  "testimonails",
  TestimonailsSliceVariation
>;

/**
 * Primary content in *TripRecomendations → Default → Primary*
 */
export interface TripRecomendationsSliceDefaultPrimary {
  /**
   * title field in *TripRecomendations → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_recomendations.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * recomendations field in *TripRecomendations → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_recomendations.default.primary.recomendations
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  recomendations: prismic.RichTextField;

  /**
   * cta field in *TripRecomendations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_recomendations.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * image field in *TripRecomendations → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_recomendations.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * isSurvivors field in *TripRecomendations → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: trip_recomendations.default.primary.issurvivors
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  issurvivors: prismic.BooleanField;

  /**
   * cta link field in *TripRecomendations → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_recomendations.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for TripRecomendations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripRecomendationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TripRecomendationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TripRecomendations*
 */
type TripRecomendationsSliceVariation = TripRecomendationsSliceDefault;

/**
 * TripRecomendations Shared Slice
 *
 * - **API ID**: `trip_recomendations`
 * - **Description**: TripRecomendations
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripRecomendationsSlice = prismic.SharedSlice<
  "trip_recomendations",
  TripRecomendationsSliceVariation
>;

/**
 * Primary content in *WhyEurope → Items*
 */
export interface WhyEuropeSliceDefaultItem {
  /**
   * whyEurope field in *WhyEurope → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: why_europe.items[].whyeurope
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  whyeurope: prismic.ContentRelationshipField<"whyeurope">;
}

/**
 * Default variation for WhyEurope Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyEuropeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<WhyEuropeSliceDefaultItem>
>;

/**
 * Slice variation for *WhyEurope*
 */
type WhyEuropeSliceVariation = WhyEuropeSliceDefault;

/**
 * WhyEurope Shared Slice
 *
 * - **API ID**: `why_europe`
 * - **Description**: WhyEurope
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyEuropeSlice = prismic.SharedSlice<
  "why_europe",
  WhyEuropeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HowDoesItWorkDocument,
      HowDoesItWorkDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ReasonsDocument,
      ReasonsDocumentData,
      RouteCardDocument,
      RouteCardDocumentData,
      RoutesDocument,
      RoutesDocumentData,
      TestimonailDocument,
      TestimonailDocumentData,
      WhyeuropeDocument,
      WhyeuropeDocumentData,
      AllDocumentTypes,
      AdvantagesSlice,
      AdvantagesSliceDefaultPrimary,
      AdvantagesSliceVariation,
      AdvantagesSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      ContactUsSlice,
      ContactUsSliceDefaultPrimary,
      ContactUsSliceVariation,
      ContactUsSliceDefault,
      CustomBudgetsSlice,
      CustomBudgetsSliceDefaultPrimary,
      CustomBudgetsSliceVariation,
      CustomBudgetsSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      ForMoreInfoContactSlice,
      ForMoreInfoContactSliceDefaultPrimary,
      ForMoreInfoContactSliceVariation,
      ForMoreInfoContactSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HotelsSlice,
      HotelsSliceDefaultPrimary,
      HotelsSliceVariation,
      HotelsSliceDefault,
      HowDoesItWorkSlice,
      HowDoesItWorkSliceDefaultPrimary,
      HowDoesItWorkSliceDefaultItem,
      HowDoesItWorkSliceVariation,
      HowDoesItWorkSliceDefault,
      InsuranceSlice,
      InsuranceSliceDefaultPrimary,
      InsuranceSliceVariation,
      InsuranceSliceDefault,
      MundorailRoutesSlice,
      MundorailRoutesSliceDefaultPrimary,
      MundorailRoutesSliceDefaultItem,
      MundorailRoutesSliceVariation,
      MundorailRoutesSliceDefault,
      NavigationSlice,
      NavigationSliceDefaultPrimary,
      NavigationSliceNegativePrimary,
      NavigationSlicePositivePrimary,
      NavigationSliceVariation,
      NavigationSliceDefault,
      NavigationSliceNegative,
      NavigationSlicePositive,
      OurRoutesSlice,
      OurRoutesSliceDefaultPrimary,
      OurRoutesSliceVariation,
      OurRoutesSliceDefault,
      OurTeamSlice,
      OurTeamSliceDefaultPrimary,
      OurTeamSliceVariation,
      OurTeamSliceDefault,
      ReasonsSlice,
      ReasonsSliceDefaultPrimary,
      ReasonsSliceDefaultItem,
      ReasonsSliceVariation,
      ReasonsSliceDefault,
      RouteCardSlice,
      RouteCardSliceDefaultPrimary,
      RouteCardSliceDefaultItem,
      RouteCardSliceVariation,
      RouteCardSliceDefault,
      RouteHeroSlice,
      RouteHeroSliceDefaultPrimary,
      RouteHeroSliceVariation,
      RouteHeroSliceDefault,
      RoutesConditionsSlice,
      RoutesConditionsSliceDefaultPrimary,
      RoutesConditionsSliceVariation,
      RoutesConditionsSliceDefault,
      RoutesDescriptionSlice,
      RoutesDescriptionSliceDefaultPrimary,
      RoutesDescriptionSliceVariation,
      RoutesDescriptionSliceDefault,
      SurvivorsSlice,
      SurvivorsSliceDefaultPrimary,
      SurvivorsSliceVariation,
      SurvivorsSliceDefault,
      TestimonailsSlice,
      TestimonailsSliceDefaultPrimary,
      TestimonailsSliceDefaultItem,
      TestimonailsSliceVariation,
      TestimonailsSliceDefault,
      TripRecomendationsSlice,
      TripRecomendationsSliceDefaultPrimary,
      TripRecomendationsSliceVariation,
      TripRecomendationsSliceDefault,
      WhyEuropeSlice,
      WhyEuropeSliceDefaultItem,
      WhyEuropeSliceVariation,
      WhyEuropeSliceDefault,
    };
  }
}
